### ISSUE TITLE
Face of cursor makes underneath character invisible

### ISSUE THREAD

**Issue by al3xandru** [muirmanders/emacs-nova-theme#1]
All I can add besides the description is a screenshot:

<img width="468" alt="2018-05-07t165324-screenshot_from_safari_of_github com-936x54" src="https://user-images.githubusercontent.com/290841/39730595-69c08548-5217-11e8-9b48-d897a2a63788.png">

That is inside an Org file.  The word under cursor is Read, but as it can seen in the screenshot the letter `R` is almost invisible.

**Comment by muirrn** [comment]
Thanks for the report. What is causing the line to be highlighted? Is it a link you are mousing over? Can you also paste in the org text and provide any additional steps I might need to reproduce?

**Comment by muirmanders** [comment]
Thanks for the report. What is causing the line to be highlighted? Is it a link you are mousing over? Can you also paste in the org text and provide any additional steps I might need to reproduce?

**Comment by al3xandru** [comment]
@muirmanders 

1. (the easy part) the Org line is as simple as:

```
** DONE Read "[[https://blog.gradle.com/quantifying-the-cost-of-builds/][Quantifying the Costs of Builds | Gradle Enterprise Blog]]"
```

2.  I can't figure out yet how the whole line got highlighted in the first pace.  Trying to reproduce that.

**Comment by al3xandru** [comment]
Funny...  I have tried to reproduce the issue while using a different theme :-).

Simply moving the cursor to the line highlights the whole line.  Next the cursor itself seems to be configured with a foreground that is very close to the line highlight background.

**Comment by muirmanders** [comment]
I can't reproduce the line being highlighted like your screenshot. I turned on `global-hl-line-mode` which highlights the current line everywhere, but the cursor color is properly inverted:

<img width="803" alt="screen shot 2018-05-08 at 11 25 31" src="https://user-images.githubusercontent.com/1671411/39734503-8df109c4-52b2-11e8-89df-b0c3176a2366.png">

Can you try starting emacs without your desktop file and without any other theme/color config and see if it reproduces?

**Comment by al3xandru** [comment]
That looks OK indeed.  

Unfortunately the no-config option is not really an option I can try as I'm running Spacemacs. I did check and indeed `global-hl-line-mode` is on here too.

What is the face used for that cursor point?  I could attempt a local fix

**Comment by muirmanders** [comment]
Spacemacs seems to keep resetting the cursor back to light blue (happens for all themes loaded via `load-theme`). Do you have to use a different mechanism to load themes in spacemacs? I have no experience with it.

**Comment by al3xandru** [comment]
The behavior seems to be the same while using the "spacemacs" approach:

1.  declare the theme inside `dotspacemacs-additional-packages` (see https://github.com/al3xandru/dotfiles/blob/master/.spacemacs#L70)

2.  set the theme in `dotspacemacs-themes` (see https://github.com/al3xandru/dotfiles/blob/master/.spacemacs#L134)

After starting Spacemacs you can switch themes using: `SPC T n` (cycle through themes in `dotspacemacs-themes`) or `SPC T s` (`counsel-load-theme`)

That's all I know :-).

- - -

_Update_: there's a Spacemacs layer that allows altering a theme before it's loaded.  I have tried this approach too, but it didn't work either. You can see how that works https://github.com/al3xandru/dotfiles/blob/master/.spacemacs#L241 (it doesn't include my tests with nova)

**Comment by al3xandru** [comment]
> Spacemacs seems to keep resetting the cursor back to light blue

It finally clicked!  There's a setting in Spacemacs `dotspacemacs-colorize-cursor-according-to-state` which is set to true will change the color of the cursor disregarding the theme.

With the multiple states that Spacemacs supports, coloring the cursor according to the state is a nice visual cue.
